In [1]:
import boto3
import csv
import pandas as pd

In [2]:
s3_client = boto3.client('s3')

In [3]:
path='s3://cloud-task/single_family_home_values.csv'

In [4]:
df=pd.read_csv(path)

In [8]:
!pip install awswrangler

Collecting awswrangler
  Using cached https://files.pythonhosted.org/packages/06/d7/061a8f66c8711d9523004a95637ac0c5e938b91595eaa306c3e5d59c1675/awswrangler-2.14.0-py3-none-any.whl
Requirement already satisfied: pymysql<1.1.0,>=0.9.0 in c:\users\lucif\anaconda3\lib\site-packages (from awswrangler) (1.0.2)
Requirement already satisfied: pandas<1.4.0,>=1.2.0; python_full_version >= "3.7.1" and python_full_version < "4.0.0" in c:\users\lucif\appdata\roaming\python\python37\site-packages (from awswrangler) (1.2.4)
Requirement already satisfied: numpy<2.0.0,>=1.21.0; python_full_version >= "3.7.1" and python_full_version < "4.0.0" in c:\users\lucif\anaconda3\lib\site-packages (from awswrangler) (1.21.5)
Requirement already satisfied: redshift-connector<2.1.0,>=2.0.889 in c:\users\lucif\anaconda3\lib\site-packages (from awswrangler) (2.0.903)
Requirement already satisfied: botocore<2.0.0,>=1.23.17 in c:\users\lucif\anaconda3\lib\site-packages (from awswrangler) (1.23.24)
Requirement already satisfied: requests-aws4auth<2.0.0,>=1.1.1 in c:\users\lucif\anaconda3\lib\site-packages (from awswrangler) (1.1.1)
Collecting progressbar2<4.0.0,>=3.53.3 (from awswrangler)
  Using cached https://files.pythonhosted.org/packages/ed/19/afcfa7b88021a172f4f5308ca3cd95709c6ac39787caa720576e4b6cf6ba/progressbar2-3.55.0-py2.py3-none-any.whl
Collecting jsonpath-ng<2.0.0,>=1.5.3 (from awswrangler)
  Using cached https://files.pythonhosted.org/packages/4c/b7/3627068d9aa6b2d49af117eb3897770a5dbc6bb3f4c09ed56a9eb749438e/jsonpath_ng-1.5.3-py3-none-any.whl
Requirement already satisfied: boto3<2.0.0,>=1.20.17 in c:\users\lucif\anaconda3\lib\site-packages (from awswrangler) (1.20.46)
Collecting openpyxl<3.1.0,>=3.0.0 (from awswrangler)
  Using cached https://files.pythonhosted.org/packages/1c/a6/8ce4d2ef2c29be3235c08bb00e0b81e29d38ebc47d82b17af681bf662b74/openpyxl-3.0.9-py2.py3-none-any.whl
Requirement already satisfied: opensearch-py<2.0.0,>=1.0.0 in c:\users\lucif\anaconda3\lib\site-packages (from awswrangler) (1.0.0)
Collecting pg8000<1.23.0,>=1.16.0 (from awswrangler)
  Using cached https://files.pythonhosted.org/packages/f2/78/90a2fcf994ddf37cabb92c148e5bc919353d76407cc673ef799d49995e4a/pg8000-1.22.1-py3-none-any.whl
Collecting pyarrow<6.1.0,>=2.0.0 (from awswrangler)
  Using cached https://files.pythonhosted.org/packages/34/bb/81ad77d518e976216b34c1e462734f4cb6eacbada32d597b0ba1b471961b/pyarrow-6.0.1-cp37-cp37m-win_amd64.whl
Requirement already satisfied: pytz>=2017.3 in c:\users\lucif\anaconda3\lib\site-packages (from pandas<1.4.0,>=1.2.0; python_full_version >= "3.7.1" and python_full_version < "4.0.0"->awswrangler) (2018.7)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\lucif\anaconda3\lib\site-packages (from pandas<1.4.0,>=1.2.0; python_full_version >= "3.7.1" and python_full_version < "4.0.0"->awswrangler) (2.7.5)
Requirement already satisfied: scramp<1.5.0,>=1.2.0 in c:\users\lucif\anaconda3\lib\site-packages (from redshift-connector<2.1.0,>=2.0.889->awswrangler) (1.4.1)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.7.0 in c:\users\lucif\anaconda3\lib\site-packages (from redshift-connector<2.1.0,>=2.0.889->awswrangler) (4.10.0)
Requirement already satisfied: lxml>=4.6.5 in c:\users\lucif\anaconda3\lib\site-packages (from redshift-connector<2.1.0,>=2.0.889->awswrangler) (4.7.1)
Requirement already satisfied: requests<2.27.2,>=2.23.0 in c:\users\lucif\appdata\roaming\python\python37\site-packages (from redshift-connector<2.1.0,>=2.0.889->awswrangler) (2.25.1)
Requirement already satisfied: packaging in c:\users\lucif\anaconda3\lib\site-packages (from redshift-connector<2.1.0,>=2.0.889->awswrangler) (18.0)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\users\lucif\anaconda3\lib\site-packages (from botocore<2.0.0,>=1.23.17->awswrangler) (0.10.0)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in c:\users\lucif\anaconda3\lib\site-packages (from botocore<2.0.0,>=1.23.17->awswrangler) (1.26.8)
Requirement already satisfied: six in c:\users\lucif\anaconda3\lib\site-packages (from requests-aws4auth<2.0.0,>=1.1.1->awswrangler) (1.12.0)
Collecting python-utils>=2.3.0 (from progressbar2<4.0.0,>=3.53.3->awswrangler)
  Using cached https://files.pythonhosted.org/packages/b5/04/78b4562436580e06ffc4518c051c3d9311d9947c8b47c7913867314887ba/python_utils-3.1.0-py2.py3-none-any.whl
Requirement already satisfied: ply in c:\users\lucif\anaconda3\lib\site-packages (from jsonpath-ng<2.0.0,>=1.5.3->awswrangler) (3.11)
Requirement already satisfied: decorator in c:\users\lucif\anaconda3\lib\site-packages (from jsonpath-ng<2.0.0,>=1.5.3->awswrangler) (4.3.0)
Requirement already satisfied: s3transfer<0.6.0,>=0.5.0 in c:\users\lucif\anaconda3\lib\site-packages (from boto3<2.0.0,>=1.20.17->awswrangler) (0.5.0)
Requirement already satisfied: et-xmlfile in c:\users\lucif\anaconda3\lib\site-packages (from openpyxl<3.1.0,>=3.0.0->awswrangler) (1.0.1)
Requirement already satisfied: certifi in c:\users\lucif\anaconda3\lib\site-packages (from opensearch-py<2.0.0,>=1.0.0->awswrangler) (2021.10.8)
Requirement already satisfied: asn1crypto>=1.4.0 in c:\users\lucif\anaconda3\lib\site-packages (from scramp<1.5.0,>=1.2.0->redshift-connector<2.1.0,>=2.0.889->awswrangler) (1.4.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\lucif\anaconda3\lib\site-packages (from beautifulsoup4<5.0.0,>=4.7.0->redshift-connector<2.1.0,>=2.0.889->awswrangler) (2.3.1)
Requirement already satisfied: idna<3,>=2.5 in c:\users\lucif\anaconda3\lib\site-packages (from requests<2.27.2,>=2.23.0->redshift-connector<2.1.0,>=2.0.889->awswrangler) (2.8)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\lucif\anaconda3\lib\site-packages (from requests<2.27.2,>=2.23.0->redshift-connector<2.1.0,>=2.0.889->awswrangler) (3.0.4)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\lucif\anaconda3\lib\site-packages (from packaging->redshift-connector<2.1.0,>=2.0.889->awswrangler) (2.3.0)
Installing collected packages: python-utils, progressbar2, jsonpath-ng, openpyxl, pg8000, pyarrow, awswrangler
  Found existing installation: openpyxl 2.5.12
    Uninstalling openpyxl-2.5.12:
      Successfully uninstalled openpyxl-2.5.12
Successfully installed awswrangler-2.14.0 jsonpath-ng-1.5.3 openpyxl-3.0.9 pg8000-1.22.1 progressbar2-3.55.0 pyarrow-6.0.1 python-utils-3.1.0

In [5]:
df.head()

,id,address,city,state,zipcode,latitude,longitude,bedrooms,bathrooms,rooms,squareFootage,lotSize,yearBuilt,lastSaleDate,lastSaleAmount,priorSaleDate,priorSaleAmount,estimated_value
0,39525749,8171 E 84th Ave,Denver,CO,80022,39.849160,-104.893468,3,2.0,6,1378,9968,2003.0,2009-12-17,75000,2004-05-13,165700.0,239753
1,184578398,10556 Wheeling St,Denver,CO,80022,39.888020,-104.830930,2,2.0,6,1653,6970,2004.0,2004-09-23,216935,NaN,NaN,343963
2,184430015,3190 Wadsworth Blvd,Denver,CO,80033,39.761710,-105.081070,3,1.0,0,1882,23875,1917.0,2008-04-03,330000,NaN,NaN,488840
3,155129946,3040 Wadsworth Blvd,Denver,CO,80033,39.760780,-105.081060,4,3.0,0,2400,11500,1956.0,2008-12-02,185000,2008-06-27,0.0,494073
4,245107,5615 S Eaton St,Denver,CO,80123,39.616181,-105.058812,3,4.0,8,2305,5600,1998.0,2012-07-18,308000,2011-12-29,0.0,513676

In [7]:
df1=df[["id","address","city","state","zipcode","squareFootage","lotSize","estimated_value"]]

In [8]:
df1.head()

,id,address,city,state,zipcode,squareFootage,lotSize,estimated_value
0,39525749,8171 E 84th Ave,Denver,CO,80022,1378,9968,239753
1,184578398,10556 Wheeling St,Denver,CO,80022,1653,6970,343963
2,184430015,3190 Wadsworth Blvd,Denver,CO,80033,1882,23875,488840
3,155129946,3040 Wadsworth Blvd,Denver,CO,80033,2400,11500,494073
4,245107,5615 S Eaton St,Denver,CO,80123,2305,5600,513676

In [10]:
#TO DO
## -> Calculate Pricepersquarefootage
## -> Using lambda function
## -> Create a new Column "PriceperSq_Foot"

In [12]:
def PriceperSq_Foot(a,b):
    return(a/b)

df1['PriceperSq_Foot']=df1.apply(lambda f: PriceperSq_Foot(f['estimated_value'],f['squareFootage']), axis=1)
print(df1)

              id                    address    city state  zipcode  \
0       39525749            8171 E 84th Ave  Denver    CO    80022
1      184578398          10556 Wheeling St  Denver    CO    80022
2      184430015        3190 Wadsworth Blvd  Denver    CO    80033
3      155129946        3040 Wadsworth Blvd  Denver    CO    80033
4         245107            5615 S Eaton St  Denver    CO    80123
...          ...                        ...     ...   ...      ...
14995   51411356              802 S High St  Denver    CO    80209
14996   21721153           214 S Lincoln St  Denver    CO    80209
14997   12995320              870 S Race St  Denver    CO    80209
14998   39611615         130 S Lafayette St  Denver    CO    80209
14999   42961679  100 S University Blvd # 1  Denver    CO    80209

       squareFootage  lotSize  estimated_value  PriceperSq_Foot
0               1378     9968           239753       173.986212
1               1653     6970           343963       208.084090
2               1882    23875           488840       259.744952
3               2400    11500           494073       205.863750
4               2305     5600           513676       222.852928
...              ...      ...              ...              ...
14995           2169     4950          1080081       497.962656
14996           2937     4500           807306       274.874362
14997           2937     4680          1737156       591.472932
14998           3193     4970          2008794       629.124334
14999           3193     4364          1421401       445.161604

[15000 rows x 9 columns]

C:\Users\lucif\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [13]:
df1.head()

,id,address,city,state,zipcode,squareFootage,lotSize,estimated_value,PriceperSq_Foot
0,39525749,8171 E 84th Ave,Denver,CO,80022,1378,9968,239753,173.986212
1,184578398,10556 Wheeling St,Denver,CO,80022,1653,6970,343963,208.084090
2,184430015,3190 Wadsworth Blvd,Denver,CO,80033,1882,23875,488840,259.744952
3,155129946,3040 Wadsworth Blvd,Denver,CO,80033,2400,11500,494073,205.863750
4,245107,5615 S Eaton St,Denver,CO,80123,2305,5600,513676,222.852928

In [14]:
priceper_sq_footage=df1.to_csv(r"S:\\ML_AI_DS\MY_TASKS\\priceper_sq_footage.csv") ##Local Storage

In [25]:
df1.to_excel (r"S:\\ML_AI_DS\MY_TASKS\\priceper_sq_footage.xlsx", index = None, header=True)

In [15]:
from io import StringIO

In [28]:
filename = 'priceper_sq_footage.xlsx'
bucketName = 'cloud-task'

csv_buffer=StringIO()
df.to_csv(csv_buffer)


##Create a client
client = boto3.client('s3')

response = client.put_object(
ACL='public',
Body=csv_buffer.getvalue(),
Bucket=bucketName,
Key=filename
)

ClientError: An error occurred (InvalidArgument) when calling the PutObject operation: None

In [29]:
df1.to_csv('s3://cloud-task/priceper_sq_footage.csv') ##File successfully uploaded