In [1]:
from prefect import task, Flow

In [2]:
import pandas as pd
import numpy as np ##to work with arrays

In [3]:
df=pd.read_csv("S:\\ML_AI_DS\\\MY_TASKS\\sample_dataset.csv")

In [4]:
df.head(5)

   S.No  order date   time                                       product_info
0     1  22/07/2021  15:45  [{\n    "id": 1,\n    "product_id": "33-745-50...
1     2  21/10/2021  20:37  [{\n    "id": 3,\n    "product_id": "48-081-02...
2     3  21/04/2021  15:15  [{\n    "id": 6,\n    "product_id": "31-992-73...
3     4  20/10/2021  05:35  [{\n    "id": 7,\n    "product_id": "99-904-84...
4     5  23/05/2021  14:04  [{\n    "id": 10,\n    "product_id": "37-943-6...

In [5]:
df.tail(5)

    S.No  order date   time                                       product_info
24    25  19/08/2021  15:46  [{\n    "id": 7,\n    "product_id": "99-904-84...
25    26  31/10/2021  21:33  [{\n    "id": 1,\n    "product_id": "33-745-50...
26    27  08/12/2021  10:05  [{\n    "id": 3,\n    "product_id": "48-081-02...
27    28  20/10/2021  09:36  [{\n    "id": 6,\n    "product_id": "31-992-73...
28    29  04/05/2021  10:34  [{\n    "id": 7,\n    "product_id": "99-904-84...

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   S.No          29 non-null     int64
 1   order date    29 non-null     object
 2   time          29 non-null     object
 3   product_info  29 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.0+ KB

In [7]:
df.shape

(29, 4)

In [8]:
df1=df['product_info']

In [9]:
df1.head(5)

0    [{\n    "id": 1,\n    "product_id": "33-745-50...
1    [{\n    "id": 3,\n    "product_id": "48-081-02...
2    [{\n    "id": 6,\n    "product_id": "31-992-73...
3    [{\n    "id": 7,\n    "product_id": "99-904-84...
4    [{\n    "id": 10,\n    "product_id": "37-943-6...
Name: product_info, dtype: object

In [10]:
df2=df['order date']

In [11]:
df2.head(5)

0    22/07/2021
1    21/10/2021
2    21/04/2021
3    20/10/2021
4    23/05/2021
Name: order date, dtype: object

In [12]:
df2_neat = df.rename(columns = {'order date': 'date'}, inplace = False)

In [13]:
df2_neat.head(5)

   S.No        date   time                                       product_info
0     1  22/07/2021  15:45  [{\n    "id": 1,\n    "product_id": "33-745-50...
1     2  21/10/2021  20:37  [{\n    "id": 3,\n    "product_id": "48-081-02...
2     3  21/04/2021  15:15  [{\n    "id": 6,\n    "product_id": "31-992-73...
3     4  20/10/2021  05:35  [{\n    "id": 7,\n    "product_id": "99-904-84...
4     5  23/05/2021  14:04  [{\n    "id": 10,\n    "product_id": "37-943-6...

In [14]:
#Convert "order date" Dtype from Object to datetime
pd.to_datetime(df2_neat.date)

0    2021-07-22
1    2021-10-21
2    2021-04-21
3    2021-10-20
4    2021-05-23
5    2021-09-02
6    2021-09-10
7    2021-10-05
8    2021-11-23
9    2021-12-23
10   2021-02-28
11   2021-06-22
12   2021-07-07
13   2021-07-07
14   2021-03-26
15   2022-09-01
16   2021-06-28
17   2021-11-26
18   2021-04-05
19   2021-06-16
20   2022-01-01
21   2021-09-14
22   2021-06-04
23   2021-07-07
24   2021-08-19
25   2021-10-31
26   2021-08-12
27   2021-10-20
28   2021-04-05
Name: date, dtype: datetime64[ns]

In [15]:
df2_neat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   S.No          29 non-null     int64
 1   date          29 non-null     object
 2   time          29 non-null     object
 3   product_info  29 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.0+ KB

In [16]:
df2_neat['date']=pd.to_datetime(df2_neat.date) #Assign

In [17]:
df2_neat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   S.No          29 non-null     int64
 1   date          29 non-null     datetime64[ns]
 2   time          29 non-null     object
 3   product_info  29 non-null     object
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 1.0+ KB

In [18]:
df2_neat['date_new'] = df2_neat['date'].dt.strftime('%B-%Y')

In [19]:
df2_neat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   S.No          29 non-null     int64
 1   date          29 non-null     datetime64[ns]
 2   time          29 non-null     object
 3   product_info  29 non-null     object
 4   date_new      29 non-null     object
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 1.3+ KB

In [20]:
df2_neat.head(5)

,S.No,date,time,product_info,date_new
0,1,2021-07-22,15:45,"[{\n ""id"": 1,\n ""product_id"": ""33-745-50...",July-2021
1,2,2021-10-21,20:37,"[{\n ""id"": 3,\n ""product_id"": ""48-081-02...",October-2021
2,3,2021-04-21,15:15,"[{\n ""id"": 6,\n ""product_id"": ""31-992-73...",April-2021
3,4,2021-10-20,05:35,"[{\n ""id"": 7,\n ""product_id"": ""99-904-84...",October-2021
4,5,2021-05-23,14:04,"[{\n ""id"": 10,\n ""product_id"": ""37-943-6...",May-2021

In [21]:
df2_neat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   S.No          29 non-null     int64
 1   date          29 non-null     datetime64[ns]
 2   time          29 non-null     object
 3   product_info  29 non-null     object
 4   date_new      29 non-null     object
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 1.3+ KB

In [22]:
pd.to_datetime(df3.time)

NameError: name 'df3' is not defined

In [23]:
df2_neat['time']=pd.to_datetime(df2_neat.time)

In [24]:
df2_neat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   S.No          29 non-null     int64
 1   date          29 non-null     datetime64[ns]
 2   time          29 non-null     datetime64[ns]
 3   product_info  29 non-null     object
 4   date_new      29 non-null     object
dtypes: datetime64[ns](2), int64(1), object(2)
memory usage: 1.3+ KB

In [25]:
df2_neat['hour'] = pd.to_datetime(df2_neat['time'], format='%H:%M:%S').dt.hour

In [26]:
df2_neat.head(5)

,S.No,date,time,product_info,date_new,hour
0,1,2021-07-22,2022-02-02 15:45:00,"[{\n ""id"": 1,\n ""product_id"": ""33-745-50...",July-2021,15
1,2,2021-10-21,2022-02-02 20:37:00,"[{\n ""id"": 3,\n ""product_id"": ""48-081-02...",October-2021,20
2,3,2021-04-21,2022-02-02 15:15:00,"[{\n ""id"": 6,\n ""product_id"": ""31-992-73...",April-2021,15
3,4,2021-10-20,2022-02-02 05:35:00,"[{\n ""id"": 7,\n ""product_id"": ""99-904-84...",October-2021,5
4,5,2021-05-23,2022-02-02 14:04:00,"[{\n ""id"": 10,\n ""product_id"": ""37-943-6...",May-2021,14

### Task 2

In [27]:
df4=df2_neat['product_info']

In [28]:
df4.head(5)

0    [{\n    "id": 1,\n    "product_id": "33-745-50...
1    [{\n    "id": 3,\n    "product_id": "48-081-02...
2    [{\n    "id": 6,\n    "product_id": "31-992-73...
3    [{\n    "id": 7,\n    "product_id": "99-904-84...
4    [{\n    "id": 10,\n    "product_id": "37-943-6...
Name: product_info, dtype: object

In [29]:
pd.set_option("display.max_colwidth", None)

In [30]:
df4.head(4)

0                                                                                                       [{\n    "id": 1,\n    "product_id": "33-745-5073",\n    "product name": "Betonica Rosmarinus",\n    "qty": 2,\n    "price": 8\n  }, {\n    "id": 2,\n    "product_id": "70-530-5687",\n    "product name": "Olive Oil and Lemon Antibacterial Foaming Hand Wash",\n    "qty": 2,\n    "price": 26\n  }]
1           [{\n    "id": 3,\n    "product_id": "48-081-0206",\n    "product name": "Fycompa",\n    "qty": 3,\n    "price": 91\n  }, {\n    "id": 4,\n    "product_id": "39-335-0082",\n    "product name": "Diphenhydramine Hydrochloride",\n    "qty": 9,\n    "price": 89\n  }, {\n    "id": 5,\n    "product_id": "84-589-2764",\n    "product name": "Lansoprazole",\n    "qty": 5,\n    "price": 55\n  }]
2                                                                                                                                                                                                                                                                              [{\n    "id": 6,\n    "product_id": "31-992-7300",\n    "product name": "LBEL HYDRATESS",\n    "qty": 10,\n    "price": 48\n  }]
3    [{\n    "id": 7,\n    "product_id": "99-904-8455",\n    "product name": "CELLULAR RADIANCE SUNSCREEN SPF 30",\n    "qty": 7,\n    "price": 37\n  }, {\n    "id": 8,\n    "product_id": "72-002-1241",\n    "product name": "SINGULAIR",\n    "qty": 8,\n    "price": 94\n  }, {\n    "id": 9,\n    "product_id": "11-911-3248",\n    "product name": "Drainage",\n    "qty": 9,\n    "price": 75\n  }]\n
Name: product_info, dtype: object

In [31]:
import json
from pandas import Series

In [108]:
json_cols = [0]

for column in json_cols:

    c_load = df4[column].apply(json.loads)
    c_list = list(c_load)
    c_dat = json.dumps(c_list)

    df4 = df4.join(pd.read_json(c_dat))
    df4 = df4.drop(column , axis=1)

AttributeError: 'str' object has no attribute 'apply'

In [33]:
df2_neat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   S.No          29 non-null     int64
 1   date          29 non-null     datetime64[ns]
 2   time          29 non-null     datetime64[ns]
 3   product_info  29 non-null     object
 4   date_new      29 non-null     object
 5   hour          29 non-null     int64
dtypes: datetime64[ns](2), int64(2), object(2)
memory usage: 1.5+ KB

In [37]:
df5=df2_neat[["S.No","date","product_info"]]

In [38]:
df5.head(3)

,S.No,date,product_info
0,1,2021-07-22,"[{\n ""id"": 1,\n ""product_id"": ""33-745-5073"",\n ""product name"": ""Betonica Rosmarinus"",\n ""qty"": 2,\n ""price"": 8\n }, {\n ""id"": 2,\n ""product_id"": ""70-530-5687"",\n ""product name"": ""Olive Oil and Lemon Antibacterial Foaming Hand Wash"",\n ""qty"": 2,\n ""price"": 26\n }]"
1,2,2021-10-21,"[{\n ""id"": 3,\n ""product_id"": ""48-081-0206"",\n ""product name"": ""Fycompa"",\n ""qty"": 3,\n ""price"": 91\n }, {\n ""id"": 4,\n ""product_id"": ""39-335-0082"",\n ""product name"": ""Diphenhydramine Hydrochloride"",\n ""qty"": 9,\n ""price"": 89\n }, {\n ""id"": 5,\n ""product_id"": ""84-589-2764"",\n ""product name"": ""Lansoprazole"",\n ""qty"": 5,\n ""price"": 55\n }]"
2,3,2021-04-21,"[{\n ""id"": 6,\n ""product_id"": ""31-992-7300"",\n ""product name"": ""LBEL HYDRATESS"",\n ""qty"": 10,\n ""price"": 48\n }]"

In [46]:
x=pd.DataFrame(df5.product_info.values.tolist())['product_info']
pd.json_normalize(x).head()

KeyError: 'product_info'

In [47]:
data=json.loads('product_info')

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [48]:
import findspark
findspark.init()

In [49]:
import pyspark.sql.functions as F
import pyspark as ps
from pyspark import SQLContext

In [50]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   S.No          29 non-null     int64
 1   date          29 non-null     datetime64[ns]
 2   product_info  29 non-null     object
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 824.0+ bytes

In [ ]:
spark = ps.sql.SparkSession.builder \
    .master('local[2]') \
    .appName('spark-ml') \
    .getOrCreate()

sc = spark.sparkContext

In [51]:
##Convert Json Object into Json String
df5['product_info'] = df5['product_info'].astype('|S')

C:\Users\lucif\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [52]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   S.No          29 non-null     int64
 1   date          29 non-null     datetime64[ns]
 2   product_info  29 non-null     |S377
dtypes: bytes3016(1), datetime64[ns](1), int64(1)
memory usage: 11.3 KB

In [53]:
df6 = pd.read_json('product_info.json', lines=True)

ValueError: Expected object or value

In [54]:
stdf = df5['product_info'].apply(json.loads)
pd.DataFrame(stdf.tolist())

,0,1,2
0,"{'id': 1, 'product_id': '33-745-5073', 'product name': 'Betonica Rosmarinus', 'qty': 2, 'price': 8}","{'id': 2, 'product_id': '70-530-5687', 'product name': 'Olive Oil and Lemon Antibacterial Foaming Hand Wash', 'qty': 2, 'price': 26}",None
1,"{'id': 3, 'product_id': '48-081-0206', 'product name': 'Fycompa', 'qty': 3, 'price': 91}","{'id': 4, 'product_id': '39-335-0082', 'product name': 'Diphenhydramine Hydrochloride', 'qty': 9, 'price': 89}","{'id': 5, 'product_id': '84-589-2764', 'product name': 'Lansoprazole', 'qty': 5, 'price': 55}"
2,"{'id': 6, 'product_id': '31-992-7300', 'product name': 'LBEL HYDRATESS', 'qty': 10, 'price': 48}",None,None
3,"{'id': 7, 'product_id': '99-904-8455', 'product name': 'CELLULAR RADIANCE SUNSCREEN SPF 30', 'qty': 7, 'price': 37}","{'id': 8, 'product_id': '72-002-1241', 'product name': 'SINGULAIR', 'qty': 8, 'price': 94}","{'id': 9, 'product_id': '11-911-3248', 'product name': 'Drainage', 'qty': 9, 'price': 75}"
4,"{'id': 10, 'product_id': '37-943-6902', 'product name': 'Assured Extra Strength Cold n hot', 'qty': 11, 'price': 1}","{'id': 11, 'product_id': '58-077-5323', 'product name': 'Freshmint Premium Anticavity', 'qty': 11, 'price': 64}",None
5,"{'id': 1, 'product_id': '33-745-5073', 'product name': 'Betonica Rosmarinus', 'qty': 10, 'price': 8}","{'id': 2, 'product_id': '70-530-5687', 'product name': 'Olive Oil and Lemon Antibacterial Foaming Hand Wash', 'qty': 12, 'price': 26}",None
6,"{'id': 3, 'product_id': '48-081-0206', 'product name': 'Fycompa', 'qty': 3, 'price': 91}","{'id': 4, 'product_id': '39-335-0082', 'product name': 'Diphenhydramine Hydrochloride', 'qty': 4, 'price': 89}","{'id': 5, 'product_id': '84-589-2764', 'product name': 'Lansoprazole', 'qty': 5, 'price': 55}"
7,"{'id': 6, 'product_id': '31-992-7300', 'product name': 'LBEL HYDRATESS', 'qty': 6, 'price': 48}",None,None
8,"{'id': 7, 'product_id': '99-904-8455', 'product name': 'CELLULAR RADIANCE SUNSCREEN SPF 30', 'qty': 7, 'price': 37}","{'id': 8, 'product_id': '72-002-1241', 'product name': 'SINGULAIR', 'qty': 18, 'price': 94}","{'id': 9, 'product_id': '11-911-3248', 'product name': 'Drainage', 'qty': 19, 'price': 75}"
9,"{'id': 1, 'product_id': '33-745-5073', 'product name': 'Betonica Rosmarinus', 'qty': 1, 'price': 8}","{'id': 2, 'product_id': '70-530-5687', 'product name': 'Olive Oil and Lemon Antibacterial Foaming Hand Wash', 'qty': 2, 'price': 26}",None
10,"{'id': 3, 'product_id': '48-081-0206', 'product name': 'Fycompa', 'qty': 3, 'price': 91}","{'id': 4, 'product_id': '39-335-0082', 'product name': 'Diphenhydramine Hydrochloride', 'qty': 4, 'price': 89}","{'id': 5, 'product_id': '84-589-2764', 'product name': 'Lansoprazole', 'qty': 5, 'price': 55}"
11,"{'id': 6, 'product_id': '31-992-7300', 'product name': 'LBEL HYDRATESS', 'qty': 6, 'price': 48}",None,None
12,"{'id': 7, 'product_id': '99-904-8455', 'product name': 'CELLULAR RADIANCE SUNSCREEN SPF 30', 'qty': 7, 'price': 37}","{'id': 8, 'product_id': '72-002-1241', 'product name': 'SINGULAIR', 'qty': 8, 'price': 94}","{'id': 9, 'product_id': '11-911-3248', 'product name': 'Drainage', 'qty': 9, 'price': 75}"
13,"{'id': 1, 'product_id': '33-745-5073', 'product name': 'Betonica Rosmarinus', 'qty': 1, 'price': 8}","{'id': 2, 'product_id': '70-530-5687', 'product name': 'Olive Oil and Lemon Antibacterial Foaming Hand Wash', 'qty': 2, 'price': 26}",None
14,"{'id': 3, 'product_id': '48-081-0206', 'product name': 'Fycompa', 'qty': 3, 'price': 91}","{'id': 4, 'product_id': '39-335-0082', 'product name': 'Diphenhydramine Hydrochloride', 'qty': 4, 'price': 89}","{'id': 5, 'product_id': '84-589-2764', 'product name': 'Lansoprazole', 'qty': 4, 'price': 55}"
15,"{'id': 6, 'product_id': '31-992-7300', 'product name': 'LBEL HYDRATESS', 'qty': 6, 'price': 48}",None,None
16,"{'id': 7, 'product_id': '99-904-8455', 'product name': 'CELLULAR RADIANCE SUNSCREEN SPF 30', 'qty': 7, 'price': 37}","{'id': 8, 'product_id': '72-002-1241', 'product name': 'SINGULAIR', 'qty': 8, 'price': 94}","{'id': 9, 'product_id': '11-911-3248', 'product name': 'Drainage', 'qty': 9, 'price': 75}"
17,"{'id': 1, 'product_id': '33-745-5073', 'product name': 'Betonica Rosmarinus', 'qty': 1, 'price': 8}","{'id': 2, 'product_id': '70-530-5687', 'product name': 'Olive Oil and Lemon Antibacterial Foaming Hand Wash', 'qty': 2, 'price': 26}",None
18,"{'id': 3, 'product_id': '48-081-0206', 'product name': 'Fycompa', 'qty': 3, 'price': 91}","{'id': 4, 'product_id': '39-335-0082', 'product name': 'Diphenhydramine Hydrochloride', 'qty': 4, 'price': 89}","{'id': 5, 'product_id': '84-589-2764', 'product name': 'Lansoprazole', 'qty': 5, 'price': 55}"
19,"{'id': 6, 'product_id': '31-992-7300', 'product name': 'LBEL HYDRATESS', 'qty': 6, 'price': 48}",None,None
20,"{'id': 7, 'product_id': '99-904-8455', 'product name': 'CELLULAR RADIANCE SUNSCREEN SPF 30', 'qty': 7, 'price': 37}","{'id': 8, 'product_id': '72-002-1241', 'product name': 'SINGULAIR', 'qty': 8, 'price': 94}","{'id': 9, 'product_id': '11-911-3248', 'product name': 'Drainage', 'qty': 9, 'price': 75}"
21,"{'id': 1, 'product_id': '33-745-5073', 'product name': 'Betonica Rosmarinus', 'qty': 1, 'price': 8}","{'id': 2, 'product_id': '70-530-5687', 'product name': 'Olive Oil and Lemon Antibacterial Foaming Hand Wash', 'qty': 2, 'price': 26}",None
22,"{'id': 3, 'product_id': '48-081-0206', 'product name': 'Fycompa', 'qty': 3, 'price': 91}","{'id': 4, 'product_id': '39-335-0082', 'product name': 'Diphenhydramine Hydrochloride', 'qty': 4, 'price': 89}","{'id': 5, 'product_id': '84-589-2764', 'product name': 'Lansoprazole', 'qty': 5, 'price': 55}"
23,"{'id': 6, 'product_id': '31-992-7300', 'product name': 'LBEL HYDRATESS', 'qty': 6, 'price': 48}",None,None
24,"{'id': 7, 'product_id': '99-904-8455', 'product name': 'CELLULAR RADIANCE SUNSCREEN SPF 30', 'qty': 7, 'price': 37}","{'id': 8, 'product_id': '72-002-1241', 'product name': 'SINGULAIR', 'qty': 8, 'price': 94}","{'id': 9, 'product_id': '11-911-3248', 'product name': 'Drainage', 'qty': 9, 'price': 75}"
25,"{'id': 1, 'product_id': '33-745-5073', 'product name': 'Betonica Rosmarinus', 'qty': 1, 'price': 8}","{'id': 2, 'product_id': '70-530-5687', 'product name': 'Olive Oil and Lemon Antibacterial Foaming Hand Wash', 'qty': 2, 'price': 26}",None
26,"{'id': 3, 'product_id': '48-081-0206', 'product name': 'Fycompa', 'qty': 3, 'price': 91}","{'id': 4, 'product_id': '39-335-0082', 'product name': 'Diphenhydramine Hydrochloride', 'qty': 4, 'price': 89}","{'id': 5, 'product_id': '84-589-2764', 'product name': 'Lansoprazole', 'qty': 5, 'price': 55}"
27,"{'id': 6, 'product_id': '31-992-7300', 'product name': 'LBEL HYDRATESS', 'qty': 6, 'price': 48}",None,None
28,"{'id': 7, 'product_id': '99-904-8455', 'product name': 'CELLULAR RADIANCE SUNSCREEN SPF 30', 'qty': 7, 'price': 37}","{'id': 8, 'product_id': '72-002-1241', 'product name': 'SINGULAIR', 'qty': 8, 'price': 94}","{'id': 9, 'product_id': '11-911-3248', 'product name': 'Drainage', 'qty': 9, 'price': 75}"

In [55]:
df5.join(df5['product_info'].apply(json.loads).apply(pd.Series))

,S.No,date,product_info,0,1,2
0,1,2021-07-22,"b'[{\n ""id"": 1,\n ""product_id"": ""33-745-5073"",\n ""product name"": ""Betonica Rosmarinus"",\n ""qty"": 2,\n ""price"": 8\n }, {\n ""id"": 2,\n ""product_id"": ""70-530-5687"",\n ""product name"": ""Olive Oil and Lemon Antibacterial Foaming Hand Wash"",\n ""qty"": 2,\n ""price"": 26\n }]'","{'id': 1, 'product_id': '33-745-5073', 'product name': 'Betonica Rosmarinus', 'qty': 2, 'price': 8}","{'id': 2, 'product_id': '70-530-5687', 'product name': 'Olive Oil and Lemon Antibacterial Foaming Hand Wash', 'qty': 2, 'price': 26}",NaN
1,2,2021-10-21,"b'[{\n ""id"": 3,\n ""product_id"": ""48-081-0206"",\n ""product name"": ""Fycompa"",\n ""qty"": 3,\n ""price"": 91\n }, {\n ""id"": 4,\n ""product_id"": ""39-335-0082"",\n ""product name"": ""Diphenhydramine Hydrochloride"",\n ""qty"": 9,\n ""price"": 89\n }, {\n ""id"": 5,\n ""product_id"": ""84-589-2764"",\n ""product name"": ""Lansoprazole"",\n ""qty"": 5,\n ""price"": 55\n }]'","{'id': 3, 'product_id': '48-081-0206', 'product name': 'Fycompa', 'qty': 3, 'price': 91}","{'id': 4, 'product_id': '39-335-0082', 'product name': 'Diphenhydramine Hydrochloride', 'qty': 9, 'price': 89}","{'id': 5, 'product_id': '84-589-2764', 'product name': 'Lansoprazole', 'qty': 5, 'price': 55}"
2,3,2021-04-21,"b'[{\n ""id"": 6,\n ""product_id"": ""31-992-7300"",\n ""product name"": ""LBEL HYDRATESS"",\n ""qty"": 10,\n ""price"": 48\n }]'","{'id': 6, 'product_id': '31-992-7300', 'product name': 'LBEL HYDRATESS', 'qty': 10, 'price': 48}",NaN,NaN
3,4,2021-10-20,"b'[{\n ""id"": 7,\n ""product_id"": ""99-904-8455"",\n ""product name"": ""CELLULAR RADIANCE SUNSCREEN SPF 30"",\n ""qty"": 7,\n ""price"": 37\n }, {\n ""id"": 8,\n ""product_id"": ""72-002-1241"",\n ""product name"": ""SINGULAIR"",\n ""qty"": 8,\n ""price"": 94\n }, {\n ""id"": 9,\n ""product_id"": ""11-911-3248"",\n ""product name"": ""Drainage"",\n ""qty"": 9,\n ""price"": 75\n }]\n '","{'id': 7, 'product_id': '99-904-8455', 'product name': 'CELLULAR RADIANCE SUNSCREEN SPF 30', 'qty': 7, 'price': 37}","{'id': 8, 'product_id': '72-002-1241', 'product name': 'SINGULAIR', 'qty': 8, 'price': 94}","{'id': 9, 'product_id': '11-911-3248', 'product name': 'Drainage', 'qty': 9, 'price': 75}"
4,5,2021-05-23,"b'[{\n ""id"": 10,\n ""product_id"": ""37-943-6902"",\n ""product name"": ""Assured Extra Strength Cold n hot"",\n ""qty"": 11,\n ""price"": 1\n }, {\n ""id"": 11,\n ""product_id"": ""58-077-5323"",\n ""product name"": ""Freshmint Premium Anticavity"",\n ""qty"": 11,\n ""price"": 64\n }]'","{'id': 10, 'product_id': '37-943-6902', 'product name': 'Assured Extra Strength Cold n hot', 'qty': 11, 'price': 1}","{'id': 11, 'product_id': '58-077-5323', 'product name': 'Freshmint Premium Anticavity', 'qty': 11, 'price': 64}",NaN
5,6,2021-09-02,"b'[{\n ""id"": 1,\n ""product_id"": ""33-745-5073"",\n ""product name"": ""Betonica Rosmarinus"",\n ""qty"": 10,\n ""price"": 8\n }, {\n ""id"": 2,\n ""product_id"": ""70-530-5687"",\n ""product name"": ""Olive Oil and Lemon Antibacterial Foaming Hand Wash"",\n ""qty"": 12,\n ""price"": 26\n }]'","{'id': 1, 'product_id': '33-745-5073', 'product name': 'Betonica Rosmarinus', 'qty': 10, 'price': 8}","{'id': 2, 'product_id': '70-530-5687', 'product name': 'Olive Oil and Lemon Antibacterial Foaming Hand Wash', 'qty': 12, 'price': 26}",NaN
6,7,2021-09-10,"b'[{\n ""id"": 3,\n ""product_id"": ""48-081-0206"",\n ""product name"": ""Fycompa"",\n ""qty"": 3,\n ""price"": 91\n }, {\n ""id"": 4,\n ""product_id"": ""39-335-0082"",\n ""product name"": ""Diphenhydramine Hydrochloride"",\n ""qty"": 4,\n ""price"": 89\n }, {\n ""id"": 5,\n ""product_id"": ""84-589-2764"",\n ""product name"": ""Lansoprazole"",\n ""qty"": 5,\n ""price"": 55\n }]'","{'id': 3, 'product_id': '48-081-0206', 'product name': 'Fycompa', 'qty': 3, 'price': 91}","{'id': 4, 'product_id': '39-335-0082', 'product name': 'Diphenhydramine Hydrochloride', 'qty': 4, 'price': 89}","{'id': 5, 'product_id': '84-589-2764', 'product name': 'Lansoprazole', 'qty': 5, 'price': 55}"
7,8,2021-10-05,"b'[{\n ""id"": 6,\n ""product_id"": ""31-992-7300"",\n ""product name"": ""LBEL HYDRATESS"",\n ""qty"": 6,\n ""price"": 48\n }]'","{'id': 6, 'product_id': '31-992-7300', 'product name': 'LBEL HYDRATESS', 'qty': 6, 'price': 48}",NaN,NaN
8,9,2021-11-23,"b'[{\n ""id"": 7,\n ""product_id"": ""99-904-8455"",\n ""product name"": ""CELLULAR RADIANCE SUNSCREEN SPF 30"",\n ""qty"": 7,\n ""price"": 37\n }, {\n ""id"": 8,\n ""product_id"": ""72-002-1241"",\n ""product name"": ""SINGULAIR"",\n ""qty"": 18,\n ""price"": 94\n }, {\n ""id"": 9,\n ""product_id"": ""11-911-3248"",\n ""product name"": ""Drainage"",\n ""qty"": 19,\n ""price"": 75\n }]\n '","{'id': 7, 'product_id': '99-904-8455', 'product name': 'CELLULAR RADIANCE SUNSCREEN SPF 30', 'qty': 7, 'price': 37}","{'id': 8, 'product_id': '72-002-1241', 'product name': 'SINGULAIR', 'qty': 18, 'price': 94}","{'id': 9, 'product_id': '11-911-3248', 'product name': 'Drainage', 'qty': 19, 'price': 75}"
9,10,2021-12-23,"b'[{\n ""id"": 1,\n ""product_id"": ""33-745-5073"",\n ""product name"": ""Betonica Rosmarinus"",\n ""qty"": 1,\n ""price"": 8\n }, {\n ""id"": 2,\n ""product_id"": ""70-530-5687"",\n ""product name"": ""Olive Oil and Lemon Antibacterial Foaming Hand Wash"",\n ""qty"": 2,\n ""price"": 26\n }]'","{'id': 1, 'product_id': '33-745-5073', 'product name': 'Betonica Rosmarinus', 'qty': 1, 'price': 8}","{'id': 2, 'product_id': '70-530-5687', 'product name': 'Olive Oil and Lemon Antibacterial Foaming Hand Wash', 'qty': 2, 'price': 26}",NaN
10,11,2021-02-28,"b'[{\n ""id"": 3,\n ""product_id"": ""48-081-0206"",\n ""product name"": ""Fycompa"",\n ""qty"": 3,\n ""price"": 91\n }, {\n ""id"": 4,\n ""product_id"": ""39-335-0082"",\n ""product name"": ""Diphenhydramine Hydrochloride"",\n ""qty"": 4,\n ""price"": 89\n }, {\n ""id"": 5,\n ""product_id"": ""84-589-2764"",\n ""product name"": ""Lansoprazole"",\n ""qty"": 5,\n ""price"": 55\n }]'","{'id': 3, 'product_id': '48-081-0206', 'product name': 'Fycompa', 'qty': 3, 'price': 91}","{'id': 4, 'product_id': '39-335-0082', 'product name': 'Diphenhydramine Hydrochloride', 'qty': 4, 'price': 89}","{'id': 5, 'product_id': '84-589-2764', 'product name': 'Lansoprazole', 'qty': 5, 'price': 55}"
11,12,2021-06-22,"b'[{\n ""id"": 6,\n ""product_id"": ""31-992-7300"",\n ""product name"": ""LBEL HYDRATESS"",\n ""qty"": 6,\n ""price"": 48\n }]'","{'id': 6, 'product_id': '31-992-7300', 'product name': 'LBEL HYDRATESS', 'qty': 6, 'price': 48}",NaN,NaN
12,13,2021-07-07,"b'[{\n ""id"": 7,\n ""product_id"": ""99-904-8455"",\n ""product name"": ""CELLULAR RADIANCE SUNSCREEN SPF 30"",\n ""qty"": 7,\n ""price"": 37\n }, {\n ""id"": 8,\n ""product_id"": ""72-002-1241"",\n ""product name"": ""SINGULAIR"",\n ""qty"": 8,\n ""price"": 94\n }, {\n ""id"": 9,\n ""product_id"": ""11-911-3248"",\n ""product name"": ""Drainage"",\n ""qty"": 9,\n ""price"": 75\n }]\n '","{'id': 7, 'product_id': '99-904-8455', 'product name': 'CELLULAR RADIANCE SUNSCREEN SPF 30', 'qty': 7, 'price': 37}","{'id': 8, 'product_id': '72-002-1241', 'product name': 'SINGULAIR', 'qty': 8, 'price': 94}","{'id': 9, 'product_id': '11-911-3248', 'product name': 'Drainage', 'qty': 9, 'price': 75}"
13,14,2021-07-07,"b'[{\n ""id"": 1,\n ""product_id"": ""33-745-5073"",\n ""product name"": ""Betonica Rosmarinus"",\n ""qty"": 1,\n ""price"": 8\n }, {\n ""id"": 2,\n ""product_id"": ""70-530-5687"",\n ""product name"": ""Olive Oil and Lemon Antibacterial Foaming Hand Wash"",\n ""qty"": 2,\n ""price"": 26\n }]'","{'id': 1, 'product_id': '33-745-5073', 'product name': 'Betonica Rosmarinus', 'qty': 1, 'price': 8}","{'id': 2, 'product_id': '70-530-5687', 'product name': 'Olive Oil and Lemon Antibacterial Foaming Hand Wash', 'qty': 2, 'price': 26}",NaN
14,15,2021-03-26,"b'[{\n ""id"": 3,\n ""product_id"": ""48-081-0206"",\n ""product name"": ""Fycompa"",\n ""qty"": 3,\n ""price"": 91\n }, {\n ""id"": 4,\n ""product_id"": ""39-335-0082"",\n ""product name"": ""Diphenhydramine Hydrochloride"",\n ""qty"": 4,\n ""price"": 89\n }, {\n ""id"": 5,\n ""product_id"": ""84-589-2764"",\n ""product name"": ""Lansoprazole"",\n ""qty"": 4,\n ""price"": 55\n }]'","{'id': 3, 'product_id': '48-081-0206', 'product name': 'Fycompa', 'qty': 3, 'price': 91}","{'id': 4, 'product_id': '39-335-0082', 'product name': 'Diphenhydramine Hydrochloride', 'qty': 4, 'price': 89}","{'id': 5, 'product_id': '84-589-2764', 'product name': 'Lansoprazole', 'qty': 4, 'price': 55}"
15,16,2022-09-01,"b'[{\n ""id"": 6,\n ""product_id"": ""31-992-7300"",\n ""product name"": ""LBEL HYDRATESS"",\n ""qty"": 6,\n ""price"": 48\n }]'","{'id': 6, 'product_id': '31-992-7300', 'product name': 'LBEL HYDRATESS', 'qty': 6, 'price': 48}",NaN,NaN
16,17,2021-06-28,"b'[{\n ""id"": 7,\n ""product_id"": ""99-904-8455"",\n ""product name"": ""CELLULAR RADIANCE SUNSCREEN SPF 30"",\n ""qty"": 7,\n ""price"": 37\n }, {\n ""id"": 8,\n ""product_id"": ""72-002-1241"",\n ""product name"": ""SINGULAIR"",\n ""qty"": 8,\n ""price"": 94\n }, {\n ""id"": 9,\n ""product_id"": ""11-911-3248"",\n ""product name"": ""Drainage"",\n ""qty"": 9,\n ""price"": 75\n }]\n '","{'id': 7, 'product_id': '99-904-8455', 'product name': 'CELLULAR RADIANCE SUNSCREEN SPF 30', 'qty': 7, 'price': 37}","{'id': 8, 'product_id': '72-002-1241', 'product name': 'SINGULAIR', 'qty': 8, 'price': 94}","{'id': 9, 'product_id': '11-911-3248', 'product name': 'Drainage', 'qty': 9, 'price': 75}"
17,18,2021-11-26,"b'[{\n ""id"": 1,\n ""product_id"": ""33-745-5073"",\n ""product name"": ""Betonica Rosmarinus"",\n ""qty"": 1,\n ""price"": 8\n }, {\n ""id"": 2,\n ""product_id"": ""70-530-5687"",\n ""product name"": ""Olive Oil and Lemon Antibacterial Foaming Hand Wash"",\n ""qty"": 2,\n ""price"": 26\n }]'","{'id': 1, 'product_id': '33-745-5073', 'product name': 'Betonica Rosmarinus', 'qty': 1, 'price': 8}","{'id': 2, 'product_id': '70-530-5687', 'product name': 'Olive Oil and Lemon Antibacterial Foaming Hand Wash', 'qty': 2, 'price': 26}",NaN
18,19,2021-04-05,"b'[{\n ""id"": 3,\n ""product_id"": ""48-081-0206"",\n ""product name"": ""Fycompa"",\n ""qty"": 3,\n ""price"": 91\n }, {\n ""id"": 4,\n ""product_id"": ""39-335-0082"",\n ""product name"": ""Diphenhydramine Hydrochloride"",\n ""qty"": 4,\n ""price"": 89\n }, {\n ""id"": 5,\n ""product_id"": ""84-589-2764"",\n ""product name"": ""Lansoprazole"",\n ""qty"": 5,\n ""price"": 55\n }]'","{'id': 3, 'product_id': '48-081-0206', 'product name': 'Fycompa', 'qty': 3, 'price': 91}","{'id': 4, 'product_id': '39-335-0082', 'product name': 'Diphenhydramine Hydrochloride', 'qty': 4, 'price': 89}","{'id': 5, 'product_id': '84-589-2764', 'product name': 'Lansoprazole', 'qty': 5, 'price': 55}"
19,20,2021-06-16,"b'[{\n ""id"": 6,\n ""product_id"": ""31-992-7300"",\n ""product name"": ""LBEL HYDRATESS"",\n ""qty"": 6,\n ""price"": 48\n }]'","{'id': 6, 'product_id': '31-992-7300', 'product name': 'LBEL HYDRATESS', 'qty': 6, 'price': 48}",NaN,NaN
20,21,2022-01-01,"b'[{\n ""id"": 7,\n ""product_id"": ""99-904-8455"",\n ""product name"": ""CELLULAR RADIANCE SUNSCREEN SPF 30"",\n ""qty"": 7,\n ""price"": 37\n }, {\n ""id"": 8,\n ""product_id"": ""72-002-1241"",\n ""product name"": ""SINGULAIR"",\n ""qty"": 8,\n ""price"": 94\n }, {\n ""id"": 9,\n ""product_id"": ""11-911-3248"",\n ""product name"": ""Drainage"",\n ""qty"": 9,\n ""price"": 75\n }]\n '","{'id': 7, 'product_id': '99-904-8455', 'product name': 'CELLULAR RADIANCE SUNSCREEN SPF 30', 'qty': 7, 'price': 37}","{'id': 8, 'product_id': '72-002-1241', 'product name': 'SINGULAIR', 'qty': 8, 'price': 94}","{'id': 9, 'product_id': '11-911-3248', 'product name': 'Drainage', 'qty': 9, 'price': 75}"
21,22,2021-09-14,"b'[{\n ""id"": 1,\n ""product_id"": ""33-745-5073"",\n ""product name"": ""Betonica Rosmarinus"",\n ""qty"": 1,\n ""price"": 8\n }, {\n ""id"": 2,\n ""product_id"": ""70-530-5687"",\n ""product name"": ""Olive Oil and Lemon Antibacterial Foaming Hand Wash"",\n ""qty"": 2,\n ""price"": 26\n }]'","{'id': 1, 'product_id': '33-745-5073', 'product name': 'Betonica Rosmarinus', 'qty': 1, 'price': 8}","{'id': 2, 'product_id': '70-530-5687', 'product name': 'Olive Oil and Lemon Antibacterial Foaming Hand Wash', 'qty': 2, 'price': 26}",NaN
22,23,2021-06-04,"b'[{\n ""id"": 3,\n ""product_id"": ""48-081-0206"",\n ""product name"": ""Fycompa"",\n ""qty"": 3,\n ""price"": 91\n }, {\n ""id"": 4,\n ""product_id"": ""39-335-0082"",\n ""product name"": ""Diphenhydramine Hydrochloride"",\n ""qty"": 4,\n ""price"": 89\n }, {\n ""id"": 5,\n ""product_id"": ""84-589-2764"",\n ""product name"": ""Lansoprazole"",\n ""qty"": 5,\n ""price"": 55\n }]'","{'id': 3, 'product_id': '48-081-0206', 'product name': 'Fycompa', 'qty': 3, 'price': 91}","{'id': 4, 'product_id': '39-335-0082', 'product name': 'Diphenhydramine Hydrochloride', 'qty': 4, 'price': 89}","{'id': 5, 'product_id': '84-589-2764', 'product name': 'Lansoprazole', 'qty': 5, 'price': 55}"
23,24,2021-07-07,"b'[{\n ""id"": 6,\n ""product_id"": ""31-992-7300"",\n ""product name"": ""LBEL HYDRATESS"",\n ""qty"": 6,\n ""price"": 48\n }]'","{'id': 6, 'product_id': '31-992-7300', 'product name': 'LBEL HYDRATESS', 'qty': 6, 'price': 48}",NaN,NaN
24,25,2021-08-19,"b'[{\n ""id"": 7,\n ""product_id"": ""99-904-8455"",\n ""product name"": ""CELLULAR RADIANCE SUNSCREEN SPF 30"",\n ""qty"": 7,\n ""price"": 37\n }, {\n ""id"": 8,\n ""product_id"": ""72-002-1241"",\n ""product name"": ""SINGULAIR"",\n ""qty"": 8,\n ""price"": 94\n }, {\n ""id"": 9,\n ""product_id"": ""11-911-3248"",\n ""product name"": ""Drainage"",\n ""qty"": 9,\n ""price"": 75\n }]\n '","{'id': 7, 'product_id': '99-904-8455', 'product name': 'CELLULAR RADIANCE SUNSCREEN SPF 30', 'qty': 7, 'price': 37}","{'id': 8, 'product_id': '72-002-1241', 'product name': 'SINGULAIR', 'qty': 8, 'price': 94}","{'id': 9, 'product_id': '11-911-3248', 'product name': 'Drainage', 'qty': 9, 'price': 75}"
25,26,2021-10-31,"b'[{\n ""id"": 1,\n ""product_id"": ""33-745-5073"",\n ""product name"": ""Betonica Rosmarinus"",\n ""qty"": 1,\n ""price"": 8\n }, {\n ""id"": 2,\n ""product_id"": ""70-530-5687"",\n ""product name"": ""Olive Oil and Lemon Antibacterial Foaming Hand Wash"",\n ""qty"": 2,\n ""price"": 26\n }]'","{'id': 1, 'product_id': '33-745-5073', 'product name': 'Betonica Rosmarinus', 'qty': 1, 'price': 8}","{'id': 2, 'product_id': '70-530-5687', 'product name': 'Olive Oil and Lemon Antibacterial Foaming Hand Wash', 'qty': 2, 'price': 26}",NaN
26,27,2021-08-12,"b'[{\n ""id"": 3,\n ""product_id"": ""48-081-0206"",\n ""product name"": ""Fycompa"",\n ""qty"": 3,\n ""price"": 91\n }, {\n ""id"": 4,\n ""product_id"": ""39-335-0082"",\n ""product name"": ""Diphenhydramine Hydrochloride"",\n ""qty"": 4,\n ""price"": 89\n }, {\n ""id"": 5,\n ""product_id"": ""84-589-2764"",\n ""product name"": ""Lansoprazole"",\n ""qty"": 5,\n ""price"": 55\n }]'","{'id': 3, 'product_id': '48-081-0206', 'product name': 'Fycompa', 'qty': 3, 'price': 91}","{'id': 4, 'product_id': '39-335-0082', 'product name': 'Diphenhydramine Hydrochloride', 'qty': 4, 'price': 89}","{'id': 5, 'product_id': '84-589-2764', 'product name': 'Lansoprazole', 'qty': 5, 'price': 55}"
27,28,2021-10-20,"b'[{\n ""id"": 6,\n ""product_id"": ""31-992-7300"",\n ""product name"": ""LBEL HYDRATESS"",\n ""qty"": 6,\n ""price"": 48\n }]'","{'id': 6, 'product_id': '31-992-7300', 'product name': 'LBEL HYDRATESS', 'qty': 6, 'price': 48}",NaN,NaN
28,29,2021-04-05,"b'[{\n ""id"": 7,\n ""product_id"": ""99-904-8455"",\n ""product name"": ""CELLULAR RADIANCE SUNSCREEN SPF 30"",\n ""qty"": 7,\n ""price"": 37\n }, {\n ""id"": 8,\n ""product_id"": ""72-002-1241"",\n ""product name"": ""SINGULAIR"",\n ""qty"": 8,\n ""price"": 94\n }, {\n ""id"": 9,\n ""product_id"": ""11-911-3248"",\n ""product name"": ""Drainage"",\n ""qty"": 9,\n ""price"": 75\n }]\n '","{'id': 7, 'product_id': '99-904-8455', 'product name': 'CELLULAR RADIANCE SUNSCREEN SPF 30', 'qty': 7, 'price': 37}","{'id': 8, 'product_id': '72-002-1241', 'product name': 'SINGULAIR', 'qty': 8, 'price': 94}","{'id': 9, 'product_id': '11-911-3248', 'product name': 'Drainage', 'qty': 9, 'price': 75}"

In [57]:
df5.tail(7)

,S.No,date,product_info
22,23,2021-06-04,"b'[{\n ""id"": 3,\n ""product_id"": ""48-081-0206"",\n ""product name"": ""Fycompa"",\n ""qty"": 3,\n ""price"": 91\n }, {\n ""id"": 4,\n ""product_id"": ""39-335-0082"",\n ""product name"": ""Diphenhydramine Hydrochloride"",\n ""qty"": 4,\n ""price"": 89\n }, {\n ""id"": 5,\n ""product_id"": ""84-589-2764"",\n ""product name"": ""Lansoprazole"",\n ""qty"": 5,\n ""price"": 55\n }]'"
23,24,2021-07-07,"b'[{\n ""id"": 6,\n ""product_id"": ""31-992-7300"",\n ""product name"": ""LBEL HYDRATESS"",\n ""qty"": 6,\n ""price"": 48\n }]'"
24,25,2021-08-19,"b'[{\n ""id"": 7,\n ""product_id"": ""99-904-8455"",\n ""product name"": ""CELLULAR RADIANCE SUNSCREEN SPF 30"",\n ""qty"": 7,\n ""price"": 37\n }, {\n ""id"": 8,\n ""product_id"": ""72-002-1241"",\n ""product name"": ""SINGULAIR"",\n ""qty"": 8,\n ""price"": 94\n }, {\n ""id"": 9,\n ""product_id"": ""11-911-3248"",\n ""product name"": ""Drainage"",\n ""qty"": 9,\n ""price"": 75\n }]\n '"
25,26,2021-10-31,"b'[{\n ""id"": 1,\n ""product_id"": ""33-745-5073"",\n ""product name"": ""Betonica Rosmarinus"",\n ""qty"": 1,\n ""price"": 8\n }, {\n ""id"": 2,\n ""product_id"": ""70-530-5687"",\n ""product name"": ""Olive Oil and Lemon Antibacterial Foaming Hand Wash"",\n ""qty"": 2,\n ""price"": 26\n }]'"
26,27,2021-08-12,"b'[{\n ""id"": 3,\n ""product_id"": ""48-081-0206"",\n ""product name"": ""Fycompa"",\n ""qty"": 3,\n ""price"": 91\n }, {\n ""id"": 4,\n ""product_id"": ""39-335-0082"",\n ""product name"": ""Diphenhydramine Hydrochloride"",\n ""qty"": 4,\n ""price"": 89\n }, {\n ""id"": 5,\n ""product_id"": ""84-589-2764"",\n ""product name"": ""Lansoprazole"",\n ""qty"": 5,\n ""price"": 55\n }]'"
27,28,2021-10-20,"b'[{\n ""id"": 6,\n ""product_id"": ""31-992-7300"",\n ""product name"": ""LBEL HYDRATESS"",\n ""qty"": 6,\n ""price"": 48\n }]'"
28,29,2021-04-05,"b'[{\n ""id"": 7,\n ""product_id"": ""99-904-8455"",\n ""product name"": ""CELLULAR RADIANCE SUNSCREEN SPF 30"",\n ""qty"": 7,\n ""price"": 37\n }, {\n ""id"": 8,\n ""product_id"": ""72-002-1241"",\n ""product name"": ""SINGULAIR"",\n ""qty"": 8,\n ""price"": 94\n }, {\n ""id"": 9,\n ""product_id"": ""11-911-3248"",\n ""product name"": ""Drainage"",\n ""qty"": 9,\n ""price"": 75\n }]\n '"

In [62]:
stdf1 = stdf["0","1"].apply(json.loads)
pd.DataFrame(stdf.tolist())

KeyError: 'key of type tuple not found and not a MultiIndex'

In [65]:
data=pd.read_csv("S:\\ML_AI_DS\\MY_TASKS\\gmv_data.csv")

In [66]:
data.head()

   SNo        Date   GMV
0    1  04/12/2021  2518
1    2  18/05/2021  3483
2    3  16/09/2021  1664
3    4  15/04/2021  1720
4    5  27/11/2021  1515

In [67]:
data.tail()

    SNo        Date   GMV
24   25  24/03/2021  5162
25   26  08/06/2021  3087
26   27  21/04/2021  7475
27   28  27/08/2021  8308
28   29  16/08/2021  1281

In [69]:
stdf=df2_neat[["S.No","date","product_info","time","date_new","hour"]]

In [70]:
stdf.head()

,S.No,date,product_info,time,date_new,hour
0,1,2021-07-22,"[{\n ""id"": 1,\n ""product_id"": ""33-745-5073"",\n ""product name"": ""Betonica Rosmarinus"",\n ""qty"": 2,\n ""price"": 8\n }, {\n ""id"": 2,\n ""product_id"": ""70-530-5687"",\n ""product name"": ""Olive Oil and Lemon Antibacterial Foaming Hand Wash"",\n ""qty"": 2,\n ""price"": 26\n }]",2022-02-02 15:45:00,July-2021,15
1,2,2021-10-21,"[{\n ""id"": 3,\n ""product_id"": ""48-081-0206"",\n ""product name"": ""Fycompa"",\n ""qty"": 3,\n ""price"": 91\n }, {\n ""id"": 4,\n ""product_id"": ""39-335-0082"",\n ""product name"": ""Diphenhydramine Hydrochloride"",\n ""qty"": 9,\n ""price"": 89\n }, {\n ""id"": 5,\n ""product_id"": ""84-589-2764"",\n ""product name"": ""Lansoprazole"",\n ""qty"": 5,\n ""price"": 55\n }]",2022-02-02 20:37:00,October-2021,20
2,3,2021-04-21,"[{\n ""id"": 6,\n ""product_id"": ""31-992-7300"",\n ""product name"": ""LBEL HYDRATESS"",\n ""qty"": 10,\n ""price"": 48\n }]",2022-02-02 15:15:00,April-2021,15
3,4,2021-10-20,"[{\n ""id"": 7,\n ""product_id"": ""99-904-8455"",\n ""product name"": ""CELLULAR RADIANCE SUNSCREEN SPF 30"",\n ""qty"": 7,\n ""price"": 37\n }, {\n ""id"": 8,\n ""product_id"": ""72-002-1241"",\n ""product name"": ""SINGULAIR"",\n ""qty"": 8,\n ""price"": 94\n }, {\n ""id"": 9,\n ""product_id"": ""11-911-3248"",\n ""product name"": ""Drainage"",\n ""qty"": 9,\n ""price"": 75\n }]\n",2022-02-02 05:35:00,October-2021,5
4,5,2021-05-23,"[{\n ""id"": 10,\n ""product_id"": ""37-943-6902"",\n ""product name"": ""Assured Extra Strength Cold n hot"",\n ""qty"": 11,\n ""price"": 1\n }, {\n ""id"": 11,\n ""product_id"": ""58-077-5323"",\n ""product name"": ""Freshmint Premium Anticavity"",\n ""qty"": 11,\n ""price"": 64\n }]",2022-02-02 14:04:00,May-2021,14

In [71]:
final_dataset=pd.merge(stdf,data)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [73]:
final_dataset=pd.merge(stdf, data, left_index=True, right_index=True)

In [74]:
final_dataset.head()

,S.No,date,product_info,time,date_new,hour,SNo,Date,GMV
0,1,2021-07-22,"[{\n ""id"": 1,\n ""product_id"": ""33-745-5073"",\n ""product name"": ""Betonica Rosmarinus"",\n ""qty"": 2,\n ""price"": 8\n }, {\n ""id"": 2,\n ""product_id"": ""70-530-5687"",\n ""product name"": ""Olive Oil and Lemon Antibacterial Foaming Hand Wash"",\n ""qty"": 2,\n ""price"": 26\n }]",2022-02-02 15:45:00,July-2021,15,1,04/12/2021,2518
1,2,2021-10-21,"[{\n ""id"": 3,\n ""product_id"": ""48-081-0206"",\n ""product name"": ""Fycompa"",\n ""qty"": 3,\n ""price"": 91\n }, {\n ""id"": 4,\n ""product_id"": ""39-335-0082"",\n ""product name"": ""Diphenhydramine Hydrochloride"",\n ""qty"": 9,\n ""price"": 89\n }, {\n ""id"": 5,\n ""product_id"": ""84-589-2764"",\n ""product name"": ""Lansoprazole"",\n ""qty"": 5,\n ""price"": 55\n }]",2022-02-02 20:37:00,October-2021,20,2,18/05/2021,3483
2,3,2021-04-21,"[{\n ""id"": 6,\n ""product_id"": ""31-992-7300"",\n ""product name"": ""LBEL HYDRATESS"",\n ""qty"": 10,\n ""price"": 48\n }]",2022-02-02 15:15:00,April-2021,15,3,16/09/2021,1664
3,4,2021-10-20,"[{\n ""id"": 7,\n ""product_id"": ""99-904-8455"",\n ""product name"": ""CELLULAR RADIANCE SUNSCREEN SPF 30"",\n ""qty"": 7,\n ""price"": 37\n }, {\n ""id"": 8,\n ""product_id"": ""72-002-1241"",\n ""product name"": ""SINGULAIR"",\n ""qty"": 8,\n ""price"": 94\n }, {\n ""id"": 9,\n ""product_id"": ""11-911-3248"",\n ""product name"": ""Drainage"",\n ""qty"": 9,\n ""price"": 75\n }]\n",2022-02-02 05:35:00,October-2021,5,4,15/04/2021,1720
4,5,2021-05-23,"[{\n ""id"": 10,\n ""product_id"": ""37-943-6902"",\n ""product name"": ""Assured Extra Strength Cold n hot"",\n ""qty"": 11,\n ""price"": 1\n }, {\n ""id"": 11,\n ""product_id"": ""58-077-5323"",\n ""product name"": ""Freshmint Premium Anticavity"",\n ""qty"": 11,\n ""price"": 64\n }]",2022-02-02 14:04:00,May-2021,14,5,27/11/2021,1515

In [75]:
final_dataset.to_csv(r"S:\\ML_AI_DS\MY_TASKS\\final_dataset.csv")